### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by bdelepine** [brsynth/rpreactor#2]
From the [README](https://github.com/brsynth/rpreactor/blob/0.4.0/README.md):

> Buggy tales
> 20190110.01 -- Timeout issue
> *  Checking results: timeout neither reached... Maybe fine but strange.
> *  Checking results: bunch of error messages mentioning unknown "pool" variable (e.g. "match_error": "name 'pool' is not defined")
> *  Bug: typo led to wrongly handling Pool of process
> *  Fix: commit ca9ff17f1e @ rule_fire
> *  Imply: rerun jobs impacted (DONE, all jobs have been reran)

@tduigou, it's not clear to me if it has been fixed and the text above is merely a backlock; should we close the issue?

**Comment by tduigou** [comment]
@bdelepine, that was basically a backlog. Let's close this issue. Some jobs still neither ends, this is in issue #5
