### ISSUE TITLE
The unkillable Pool

### ISSUE THREAD

**Issue by bdelepine** [brsynth/rpreactor#5]
From the [README](https://github.com/brsynth/rpreactor/blob/0.4.0/README.md):

> Buggy tales
> 20190112.01 -- The unkillable Pool
>  * Execution hang (sometimes) when renewing the Pool (done after every time out)
>  * Due to timed out job lock that cannot be acquired (deadlock)
>  * Issue do not happen every time
>  * 100% chance of hang when the time out == 0. Hypothesis: the job was not fully initialized, cannot acquire a lock that have not been set up
>  * But hang can also happen if more "reasonable" timeout condition (e.g. 5 seconds). Hypothesis: the job have been killed while it was actually ending, something went wrong.
>  * Straightforward fix for all cases: force to release the job lock each time. Commit 52466a536e @ rule_file

**Comment by tduigou** [comment]
Weeks after, no new issue have been spotted on unkillable jobs since the introduction of `pebble` library to manage processes (merged branch associated to 1e94f19ca80603477d637f1b23e4da7d798605b2). I'm confident we can consider the bug has "solved", champagne!
